(module
    (import "io" "read" (func $readByte (result i64)))
    (import "io" "write" (func $writeByte (param $_ i64)  (result i64)))
    (import "io" "peek" (func $peekByte (result i64)))
    (export "main" (func $main))
    (func $main (result i64)
        (call $peekByte)
        (call $writeByte)
        (drop)
        (call $readByte)
        (call $writeByte)
        (drop)
        (i64.const 160)
        (call $writeByte)
        (drop)
        (i64.const 1064)
    )
)
